### ISSUE TITLE
a few notes:

### ISSUE THREAD

**Issue by pmlopes** [jaymine/TCP-eventbus-client-Python#1]
A couple of notes:
- I'd remove the compiled files `*.pyc` you can avoid then by adding a `.gitignore` file.
- The readme should have a simple paragraph explaining the project and a hello word example this way users can use it right away
- the pdf's could be encoded as markdown/asciidoc (whatever you feel easier) so they can be read directly from github site and maybe under a `docs` folder
- investigate what it takes to push it do `pypi` https://pypi.python.org/pypi

**Comment by jaymine** [comment]
1) added gitignore and removed compiled files
2) updated readme.md

**Comment by jaymine** [comment]
3) created: wik files

**Comment by jaymine** [comment]
4)the module is inserted into pypi
https://pypi.python.org/pypi/vertx-eventbus/1.0.0

**Comment by pmlopes** [comment]
nice work!
